### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [xiaoshihou514/skiff#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by xiaoshihou514** [comment]
lol sure

**Comment by xiaoshihou514** [comment]
![Screenshot from 2023-10-08 11-57-47](https://github.com/xiaoshihou514/skiff/assets/108414369/7454d84c-8a3c-4c7f-9e4b-0859b4db1396)
